feat: themed logos [CFE-75]
washingtonpost/wpds-assets-manager pull request #220
Opened 2024-12-09 04:28 UTC by artmsilva

- Replaced fill with `fill="#111"` `fill="var(--wpds-colors-primary)"`

2024-12-09 21:07 UTC, atomictangerine approved these changes

2024-12-09 21:09 UTC, atomictangerine commented on README.md
> +## Themeing
```suggestion
## Theming
```

2024-12-09 21:27 UTC, wp-aberg requested changes
This works in this case because the fallback if the var isn't present will be black. I think it's safer if we are explicit
`fill="var(--wpds-colors-primary, #111)`

2024-12-10 15:14 UTC, wp-aberg approved these changes

2024-12-10 15:35 UTC, merged